blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/tsedio/tsed/discussions
    about: Open a discussion that can be followed by the whole community on Github!
  - name: ðŸ’¬ Community channel (Slack)
    url: https://api.tsed.io/rest/slack/tsedio/tsed
    about: Join our slack workspace to discuss directly wiht the team!

